title:             Metal Mac
email:             sssurajsuraj@gmail.com
description:       Supershitty To The Max
author:            Maccy
#url:               "localhost:4000"
url:               "http://bananpizza.github.io/testmacadmin"
baseurl:

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
